// alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

//autenticacion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'
export const SELECCIONAR_MODULO = 'SELECCIONAR_MODULO'

//barra
export const MOSTRAR_BARRA = 'MOSTRAR_BARRA'
export const OCULTAR_BARRA = 'OCULTAR_BARRA'
export const CAMBIAR_MENU = 'CAMBIAR_MENU'

//cargaFactura
export const CONSULTAR_INFORMACION = 'CONSULTAR_INFORMACION'
export const CONSULTAR_ERROR = 'CONSULTAR_ERROR'

//registroObra
export const INFO_GENERAL = 'INFO_GENERAL'
export const ERROR_REGISTRO_OBRA = 'ERROR_REGISTRO_OBRA'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_CHANGE_FECHA = 'HANDLE_CHANGE_FECHA'
export const CARGAR_CONCEPTOS = 'CARGAR_CONCEPTOS'
export const CAMBIAR_ESTADO = 'CAMBIAR_ESTADO'
export const CREAR_OBRA = 'CREAR_OBRA'

//modal
export const ESTADO_MODAL = 'ESTADO_MODAL'
export const REALIZAR_PETICION = 'REALIZAR_PETICION'

//obras
export const ERROR_CARGAR_OBRAS = 'ERROR_CARGAR_OBRAS'
export const CARGAR_OBRAS = 'CARGAR_OBRAS'

//datosCliente
export const SELECCIONAR_OBRA = 'SELECCIONAR_OBRA'
export const DATOS_PERSONALES = 'DATOS_PERSONALES'
export const DATOS_FISCALES = 'DATOS_FISCALES'
export const DATOS_BANCARIOS = 'DATOS_BANCARIOS'
export const SUBMIT_CLIENTE = 'SUBMIT_CLIENTE'
export const ERROR_REGISTRO_CLIENTE = 'ERROR_REGISTRO_CLIENTE'